import Link from "next/link";
import { requireAdmin } from "@/lib/admin";
import { prisma } from "@/lib/prisma";
import AdminStatCard from "@/components/admin/AdminStatCard";

export default async function AdminNotificationsPage() {
  await requireAdmin();

  const notifications = await prisma.notification.findMany({
    orderBy: { createdAt: "desc" },
    include: {
      user: true,
    },
    take: 150,
  });

  const unread = notifications.filter((n) => !n.isRead);
  const read = notifications.filter((n) => n.isRead);
  const system = notifications.filter((n) => n.type === "SYSTEM");
  const email = notifications.filter((n) => n.type === "EMAIL");

  return (
    <main className="min-h-screen bg-[#F5F7FB] px-4 py-6 md:px-8">
      <section className="mx-auto max-w-7xl">
        <div className="mb-8 flex flex-col justify-between gap-5 md:flex-row md:items-center">
          <div>
            <p className="text-sm font-black text-[#062B8C]">
              Admin Notification Center
            </p>

            <h1 className="mt-2 text-3xl font-black text-[#06183A] md:text-4xl">
              Notifications
            </h1>

            <p className="mt-2 text-sm text-slate-500">
              Monitor all customer notifications generated by documents, loans,
              withdrawals, transfers and account activity.
            </p>
          </div>

          <Link
            href="/admin"
            className="rounded-2xl border border-slate-300 bg-white px-5 py-3 text-sm font-black"
          >
            Back to Admin Dashboard
          </Link>
        </div>

        <div className="mb-6 grid gap-4 md:grid-cols-5">
          <AdminStatCard title="Total" value={notifications.length} icon="🔔" tone="dark" />
          <AdminStatCard title="Unread" value={unread.length} icon="📩" tone="amber" />
          <AdminStatCard title="Read" value={read.length} icon="✅" tone="green" />
          <AdminStatCard title="System" value={system.length} icon="⚙️" tone="blue" />
          <AdminStatCard title="Email" value={email.length} icon="✉️" tone="red" />
        </div>

        <div className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm">
          <div className="mb-5">
            <h2 className="text-xl font-black text-[#06183A]">
              Notification history
            </h2>
            <p className="mt-1 text-sm text-slate-500">
              Latest notifications across the platform.
            </p>
          </div>

          {notifications.length === 0 ? (
            <div className="rounded-3xl bg-blue-50 p-8 text-center">
              <h3 className="text-xl font-black text-[#06183A]">
                No notifications yet
              </h3>
              <p className="mt-3 text-slate-500">
                Customer notifications will appear here.
              </p>
            </div>
          ) : (
            <div className="space-y-3">
              {notifications.map((item) => (
                <div
                  key={item.id}
                  className="rounded-2xl border border-slate-100 bg-slate-50 p-5"
                >
                  <div className="flex flex-col justify-between gap-4 md:flex-row md:items-start">
                    <div>
                      <div className="flex flex-wrap items-center gap-3">
                        <h3 className="font-black text-[#06183A]">
                          {item.title}
                        </h3>

                        <span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-black text-blue-700">
                          {item.type}
                        </span>

                        <span
                          className={`rounded-full px-3 py-1 text-xs font-black ${
                            item.isRead
                              ? "bg-emerald-100 text-emerald-700"
                              : "bg-amber-100 text-amber-700"
                          }`}
                        >
                          {item.isRead ? "Read" : "Unread"}
                        </span>
                      </div>

                      <p className="mt-2 text-sm leading-6 text-slate-600">
                        {item.message}
                      </p>

                      <div className="mt-4 grid gap-2 text-sm text-slate-500 md:grid-cols-2">
                        <p>
                          <strong>Customer:</strong> {item.user.fullName}
                        </p>
                        <p>
                          <strong>Email:</strong> {item.user.email}
                        </p>
                        <p>
                          <strong>Phone:</strong> {item.user.phone}
                        </p>
                        <p>
                          <strong>Created:</strong>{" "}
                          {new Date(item.createdAt).toLocaleString()}
                        </p>
                      </div>
                    </div>

                    <Link
                      href={`/admin/customers/${item.userId}`}
                      className="rounded-2xl bg-[#062B8C] px-4 py-3 text-center text-sm font-black text-white"
                    >
                      View customer
                    </Link>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </section>
    </main>
  );
}